manifest:
  remotes:
    - name: zmkfirmware
//      url-base: https://github.com/LOWPROKB
        url-base: https://github.com/caksoylar/zmk.git
  projects:
    - name: zmk
      remote: zmkfirmware
//      revision: Board-Corne-ish-Zen-dedicated-work-queue
      revision: zen+969+1098
      import: app/west.yml
  self:
    path: config
